server:
  port: 3535



spring:
  profiles:
    active:
      - jms-listener
  artemis:
    host: artemis.tacocloud.com
    port: 61617
    user: kitchen
    password: l3tm31n

---
spring:
  profiles:
    config:
      activate:
        on-profile: jms-listener
