server:
  port: 3535



spring:
  rabbitmq:
    template:
      receive-timeout: 1000
      exchange: tacocloud.order
      routing-key: kitchens.central

    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  profiles:
    config:
      activate:
        on-profile: jms-listener
