server:
  port: 3535



spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: order.topic
---
spring:
  profiles:
    config:
      activate:
        on-profile: jms-listener
